# Generated by Django 4.0.1 on 2022-01-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birthdate_user_currency_user_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
