# Generated by Django 4.0.1 on 2022-01-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='createdAt',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='updatedAt',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='createdAt',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updatedAt',
            new_name='updated',
        ),
    ]
